In [4]:
import numpy as np
from scipy.linalg import lu, solve

def test_fortran_lu():
    """
    Test the Fortran LU decomposition and back substitution routines
    by solving the same system in Python.
    """
    # Define a test case: A simple 3x3 system with known solution
    A = np.array([
        [2.0, -1.0, 0.0],
        [-1.0, 2.0, -1.0],
        [0.0, -1.0, 2.0]
    ])
    B = np.array([1.0, 0.0, 1.0])

    # Expected solution: X = [1, 1, 1]
    expected_solution = np.array([1.0, 1.0, 1.0])

    # Solve using Python's SciPy LU decomposition
    P, L, U = lu(A)  # SciPy LU decomposition
    Y = np.linalg.solve(L, P.T @ B)  # Forward substitution
    X = np.linalg.solve(U, Y)  # Back substitution

    # Output the results
    print("Matrix A:")
    print(A)
    print("\nVector B:")
    print(B)
    print("\nExpected Solution (X):")
    print(expected_solution)
    print("\nSolution from Python LU:")
    print(X)

    # Check the difference between expected and computed solutions
    assert np.allclose(X, expected_solution, atol=1e-6), "Python LU solution is incorrect!"
    print("\nPython LU decomposition passed the test!")

if __name__ == "__main__":
    test_fortran_lu()

Matrix A:
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]

Vector B:
[1. 0. 1.]

Expected Solution (X):
[1. 1. 1.]

Solution from Python LU:
[1. 1. 1.]

Python LU decomposition passed the test!


In [10]:
import numpy as np
from scipy.linalg import lu, solve

def test_large_system():
    """
    Test a larger 15x15 system.
    """
    # Generate a random 15x15 matrix
    np.random.seed(42)  # For reproducibility
    A = np.random.rand(15, 15) * 10

    # Make A diagonally dominant for numerical stability
    for i in range(15):
        A[i, i] += np.sum(np.abs(A[i, :]))

    # Generate a random B vector
    B = np.random.rand(15) * 10

    # Solve using Python's SciPy LU decomposition
    P, L, U = lu(A)  # SciPy LU decomposition
    Y = np.linalg.solve(L, P.T @ B)  # Forward substitution
    X = np.linalg.solve(U, Y)  # Back substitution
    X_direct = np.linalg.solve(A, B)  # Direct solver
    print("Matrix A:")
    print(A)
    print("\nVector B:")
    print(B)
    print("\nSolution from Python LU:")
    print(X)
    print("\nSolution from Python Direct:")
    print(X_direct)

    print("\nPermutation Matrix P:")
    print(P)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nUpper Triangular Matrix U:")
    print(U)
    
    return A, B, X  # Return A, B, and solution for comparison

if __name__ == "__main__":
    A, B, expected_solution = test_large_system()

Matrix A:
[[7.79300854e+01 9.50714306e+00 7.31993942e+00 5.98658484e+00
  1.56018640e+00 1.55994520e+00 5.80836122e-01 8.66176146e+00
  6.01115012e+00 7.08072578e+00 2.05844943e-01 9.69909852e+00
  8.32442641e+00 2.12339111e+00 1.81824967e+00]
 [1.83404510e+00 6.04369198e+01 5.24756432e+00 4.31945019e+00
  2.91229140e+00 6.11852895e+00 1.39493861e+00 2.92144649e+00
  3.66361843e+00 4.56069984e+00 7.85175961e+00 1.99673782e+00
  5.14234438e+00 5.92414569e+00 4.64504127e-01]
 [6.07544852e+00 1.70524124e+00 6.97746253e+01 9.48885537e+00
  9.65632033e+00 8.08397348e+00 3.04613769e+00 9.76721140e-01
  6.84233027e+00 4.40152494e+00 1.22038235e+00 4.95176910e+00
  3.43885211e-01 9.09320402e+00 2.58779982e+00]
 [6.62522284e+00 3.11711076e+00 5.20068021e+00 8.52642734e+01
  1.84854456e+00 9.69584628e+00 7.75132823e+00 9.39498942e+00
  8.94827350e+00 5.97899979e+00 9.21874235e+00 8.84925021e-01
  1.95982862e+00 4.52272889e-01 3.25330331e+00]
 [3.88677290e+00 2.71349032e+00 8.28737509e+00 3.56753

In [17]:
#!/usr/bin/env python
from numpy import array, dot
from scipy.linalg import lu

# Setup
num_layers = 15

D = ones(num_layers)
delta_h = ones(num_layers)

D[1] = 0.5
D[3] = 2.0
D[2] = 0.1

delta_h[0] = 0.25
delta_h[1] = 1.0
delta_h[2] = 1.75
delta_h[3] = 0.25

C_0 = 0
C_N = 1.0

# Set up matrices and arrays

A = np.array([
    [83.35457, 9.89760, 3.40843, 5.54044, 0.79181, 4.92283, 8.78297, 1.10094, 6.77305, 1.84765, 0.64421, 4.94708, 8.78113, 7.86865, 8.84251],
    [5.23360, 94.68575, 1.24389, 8.89201, 7.72465, 7.78681, 7.34097, 3.70172, 9.44808, 6.69294, 3.15258, 9.82203, 0.15001, 4.78221, 7.06252],
    [1.22032, 8.60004, 87.28609, 9.15963, 8.65783, 7.32497, 5.45205, 9.27386, 6.55800, 6.57679, 2.89124, 1.00065, 3.45661, 3.63345, 9.00635],
    [7.90058, 5.97920, 0.60475, 67.33809, 2.14675, 5.01093, 5.12443, 1.17485, 9.47456, 3.95087, 3.24693, 9.25343, 1.51269, 1.05959, 3.73429],
    [6.27520, 9.75004, 7.68614, 5.06515, 98.28858, 8.84355, 1.59084, 2.59832, 6.44884, 5.78087, 7.10466, 2.14041, 4.30642, 9.64804, 1.28708],
    [8.06112, 7.86698, 5.72363, 2.53535, 8.85041, 61.76400, 0.64044, 0.38424, 8.41563, 6.33276, 2.07908, 1.15365, 1.17952, 2.20602, 5.22930],
    [9.90005, 3.53900, 9.64428, 4.95311, 4.15822, 4.13764, 90.42877, 0.54926, 9.64738, 5.02764, 2.66181, 2.19172, 4.44483, 5.15444, 9.12047],
    [8.25621, 7.83167, 3.28492, 3.36158, 7.10359, 6.06495, 9.69602, 100.48293, 7.26193, 1.38950, 2.48798, 9.61342, 9.28618, 4.04681, 5.38817],
    [7.45051, 0.16652, 8.43709, 6.07144, 0.03846, 0.68480, 3.61622, 9.18608, 67.31652, 7.66512, 2.46896, 5.54103, 9.75060, 0.41502, 2.74126],
    [4.95836, 7.95106, 4.14476, 5.02218, 0.71779, 5.91644, 3.50291, 6.40518, 8.35688, 74.72064, 1.53099, 0.52296, 5.63284, 3.06243, 7.40727],
    [5.70700, 8.48362, 9.81266, 1.60724, 0.24982, 6.77009, 9.33610, 0.75623, 5.07392, 6.54999, 87.70555, 7.79047, 6.53285, 2.52304, 9.17867],
    [3.12050, 1.76461, 4.40356, 1.09056, 2.85825, 7.97043, 9.32181, 9.30598, 8.92049, 6.88026, 1.16898, 73.54960, 4.47633, 7.65447, 0.80668],
    [6.07951, 1.75471, 7.40567, 1.50393, 7.56789, 0.12236, 7.28588, 4.61457, 8.51518, 6.95761, 1.22547, 1.76697, 77.37497, 3.91683, 0.18142],
    [9.00634, 8.75670, 4.66961, 8.08642, 2.71940, 5.54528, 6.35681, 1.86923, 0.83677, 2.61280, 7.68144, 2.16520, 0.06086, 81.53604, 6.80621],
    [4.19812, 9.01949, 2.29508, 8.01184, 0.96202, 7.31440, 9.02613, 4.19202, 1.20425, 2.47400, 1.10781, 2.31614, 1.38679, 8.35878, 77.17825]
], dtype='double', order='f')

# A = array([[8, 2, 3, 12], [2, 4, 7, 0.25], [3, 7, 3, 5], [12, 0.25, 5, 2]], 
        # dtype='double', order='f')
print(A)
# b = array([25, 13.25, 18, 19.25], dtype=float64, order='f')

b = array([6.23099,   1.09295,   1.46779,   9.12107,   1.29497,   2.81819,   9.28779,   2.41123,   0.47117,   7.60806,   5.05363,   7.33092,   2.02701,   7.09238,   9.32863],dtype=float64, order='f')
print(b)

indx, d, code = lu_solver.lu.ludcmp(A, num_layers)

print("LU Decomposition:")
print (A)
print (indx)
print (d)
print (code)

if code == 0:
    lu_solver.lu.lubksb(A, num_layers, indx, b)

print("Solution:")
print (b)

[[8.3354570e+01 9.8976000e+00 3.4084300e+00 5.5404400e+00 7.9181000e-01
  4.9228300e+00 8.7829700e+00 1.1009400e+00 6.7730500e+00 1.8476500e+00
  6.4421000e-01 4.9470800e+00 8.7811300e+00 7.8686500e+00 8.8425100e+00]
 [5.2336000e+00 9.4685750e+01 1.2438900e+00 8.8920100e+00 7.7246500e+00
  7.7868100e+00 7.3409700e+00 3.7017200e+00 9.4480800e+00 6.6929400e+00
  3.1525800e+00 9.8220300e+00 1.5001000e-01 4.7822100e+00 7.0625200e+00]
 [1.2203200e+00 8.6000400e+00 8.7286090e+01 9.1596300e+00 8.6578300e+00
  7.3249700e+00 5.4520500e+00 9.2738600e+00 6.5580000e+00 6.5767900e+00
  2.8912400e+00 1.0006500e+00 3.4566100e+00 3.6334500e+00 9.0063500e+00]
 [7.9005800e+00 5.9792000e+00 6.0475000e-01 6.7338090e+01 2.1467500e+00
  5.0109300e+00 5.1244300e+00 1.1748500e+00 9.4745600e+00 3.9508700e+00
  3.2469300e+00 9.2534300e+00 1.5126900e+00 1.0595900e+00 3.7342900e+00]
 [6.2752000e+00 9.7500400e+00 7.6861400e+00 5.0651500e+00 9.8288580e+01
  8.8435500e+00 1.5908400e+00 2.5983200e+00 6.4488400e+00 5.

NameError: name 'lu_solver' is not defined

In [21]:
from numpy import array, dot
from scipy.linalg import lu

# Define the 15x15 matrix A
# A = array([
#     [83.35457, 9.89760, 3.40843, 5.54044, 0.79181, 4.92283, 8.78297, 1.10094, 6.77305, 1.84765, 0.64421, 4.94708, 8.78113, 7.86865, 8.84251],
#     [5.23360, 94.68575, 1.24389, 8.89201, 7.72465, 7.78681, 7.34097, 3.70172, 9.44808, 6.69294, 3.15258, 9.82203, 0.15001, 4.78221, 7.06252],
#     [1.22032, 8.60004, 87.28609, 9.15963, 8.65783, 7.32497, 5.45205, 9.27386, 6.55800, 6.57679, 2.89124, 1.00065, 3.45661, 3.63345, 9.00635],
#     [7.90058, 5.97920, 0.60475, 67.33809, 2.14675, 5.01093, 5.12443, 1.17485, 9.47456, 3.95087, 3.24693, 9.25343, 1.51269, 1.05959, 3.73429],
#     [6.27520, 9.75004, 7.68614, 5.06515, 98.28858, 8.84355, 1.59084, 2.59832, 6.44884, 5.78087, 7.10466, 2.14041, 4.30642, 9.64804, 1.28708],
#     [8.06112, 7.86698, 5.72363, 2.53535, 8.85041, 61.76400, 0.64044, 0.38424, 8.41563, 6.33276, 2.07908, 1.15365, 1.17952, 2.20602, 5.22930],
#     [9.90005, 3.53900, 9.64428, 4.95311, 4.15822, 4.13764, 90.42877, 0.54926, 9.64738, 5.02764, 2.66181, 2.19172, 4.44483, 5.15444, 9.12047],
#     [8.25621, 7.83167, 3.28492, 3.36158, 7.10359, 6.06495, 9.69602, 100.48293, 7.26193, 1.38950, 2.48798, 9.61342, 9.28618, 4.04681, 5.38817],
#     [7.45051, 0.16652, 8.43709, 6.07144, 0.03846, 0.68480, 3.61622, 9.18608, 67.31652, 7.66512, 2.46896, 5.54103, 9.75060, 0.41502, 2.74126],
#     [4.95836, 7.95106, 4.14476, 5.02218, 0.71779, 5.91644, 3.50291, 6.40518, 8.35688, 74.72064, 1.53099, 0.52296, 5.63284, 3.06243, 7.40727],
#     [5.70700, 8.48362, 9.81266, 1.60724, 0.24982, 6.77009, 9.33610, 0.75623, 5.07392, 6.54999, 87.70555, 7.79047, 6.53285, 2.52304, 9.17867],
#     [3.12050, 1.76461, 4.40356, 1.09056, 2.85825, 7.97043, 9.32181, 9.30598, 8.92049, 6.88026, 1.16898, 73.54960, 4.47633, 7.65447, 0.80668],
#     [6.07951, 1.75471, 7.40567, 1.50393, 7.56789, 0.12236, 7.28588, 4.61457, 8.51518, 6.95761, 1.22547, 1.76697, 77.37497, 3.91683, 0.18142],
#     [9.00634, 8.75670, 4.66961, 8.08642, 2.71940, 5.54528, 6.35681, 1.86923, 0.83677, 2.61280, 7.68144, 2.16520, 0.06086, 81.53604, 6.80621],
#     [4.19812, 9.01949, 2.29508, 8.01184, 0.96202, 7.31440, 9.02613, 4.19202, 1.20425, 2.47400, 1.10781, 2.31614, 1.38679, 8.35878, 77.17825]
# ])

# # Define the vector B
# B = array([6.23099, 1.09295, 1.46779, 9.12107, 1.29497, 2.81819, 9.28779, 2.41123, 0.47117, 7.60806, 5.05363, 7.33092, 2.02701, 7.09238, 9.32863])

A = np.array([
    [105.63266,  8.70187,  7.69997,  8.05870,  6.75063,  1.67494,  6.52307,  5.73490,  9.89792,  8.60752,  8.76980,  1.98439,  8.93282,  2.26671,  4.00564],
    [  0.41932, 72.41219,  5.59489,  7.09906,  1.78147,  3.65652,  6.55780,  4.42844,  7.23830,  0.55808,  8.82577,  7.99892,  3.11670,  8.20827,  1.15872],
    [  2.34970,  0.35454, 73.06994,  0.58892,  8.54435,  1.78643,  3.97860,  9.02092,  1.55252,  7.24601,  2.22327,  5.46663,  5.75371,  0.72768,  4.90508],
    [  0.71489,  3.52688,  8.68146, 93.26953,  1.22901,  8.13665,  7.83966,  9.71695,  6.90811,  6.86930,  5.17963,  8.64540,  5.87307,  5.88884,  1.08006],
    [  3.17940,  2.33480,  8.76195,  2.83198, 72.79372,  5.30278,  4.67560,  1.19371,  7.24537,  5.90750,  6.76517,  5.43745,  2.82544,  7.52731,  3.94403],
    [  2.44196,  0.30366,  9.54783,  0.05774,  5.62899, 81.87182,  5.00256,  2.88062,  6.28580,  3.98910,  9.34960,  6.80698,  9.71406,  8.80351,  8.86269],
    [  2.15236,  8.08510,  9.29799,  3.99106,  7.60196,  8.69502, 97.86058,  8.18893,  5.96150,  2.44047,  7.07502,  1.51596,  2.47296,  7.32446,  3.82833],
    [  1.35392,  2.27242,  7.64599,  4.58294,  0.01539,  7.94631,  2.18790, 78.10100,  9.16501,  5.79058,  2.77905,  7.97498,  5.25293,  8.48735,  8.99993],
    [  4.52972,  6.75253,  1.63602,  4.63540,  2.76705,  6.85716,  8.26591,  8.48082, 73.90777,  2.60211,  3.23350,  6.37575,  6.78065,  6.17060,  1.16903],
    [  4.80654,  7.72571,  0.55017,  8.09672,  0.07611,  6.72648,  7.99670,  9.14976,  3.20042, 91.85493,  4.45017,  8.93399,  3.48506,  7.32737,  3.37243],
    [  9.66263,  2.47869,  0.14798,  7.11123,  5.12254,  6.29804,  8.68857,  9.09580,  1.39820,  1.25417, 82.19258,  7.32023,  4.90513,  8.67975,  0.22901],
    [  9.28737,  9.60166,  4.53242,  3.62803,  1.39575,  1.21184,  5.37994,  7.17593,  6.77271,  8.20198,  7.19435, 88.02747,  0.97715,  2.40121,  9.08363],
    [  8.55614,  2.52615,  8.76586,  4.21500,  7.15207,  6.77572,  6.64340,  3.66478,  8.77690,  0.04714,  8.42329,  8.12193, 99.66620,  3.19651,  9.32968],
    [  0.54579,  5.10225,  6.76557,  3.02294,  6.08568,  9.05188,  9.06269,  7.73264,  9.32527,  9.99922,  8.13941,  8.09223,  1.79643, 95.35872,  2.37739],
    [  9.73961,  3.85148,  8.89499,  0.00701,  5.32302,  4.94879,  5.87826,  2.68586,  9.07311,  3.52190,  1.74248,  8.56276,  5.80055,  8.83806, 80.58878]
])

# Define the vector B
B = np.array([2.85894, 1.82683, 7.17248, 1.96437, 4.70392, 7.57247, 3.00031, 1.97873, 7.85266, 2.40361, 6.58986, 4.79633, 6.77246, 5.53443, 6.43082])

X = np.linalg.solve(A, B)

print("Solution vector X:")
print(X)

Solution vector X:
[-4.53413642e-05 -8.97943988e-03  8.21329722e-02 -8.31011033e-03
  2.66678882e-02  5.17775622e-02  2.76574416e-03 -1.47599251e-02
  8.90783636e-02  9.90217217e-03  6.70947776e-02  3.23803923e-02
  3.49284298e-02  2.72515126e-02  4.56614888e-02]
